# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('favorite', models.BooleanField(default=False)),
                ('added_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dropbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('access_token', models.CharField(max_length=300)),
                ('client_id', models.CharField(max_length=300)),
                ('client_secret', models.CharField(max_length=300)),
                ('redirect_uri', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('favorite', models.BooleanField(default=False)),
                ('added_at', models.DateField(auto_now_add=True)),
                ('location', models.URLField(default=None, null=True)),
                ('local_location', models.FileField(default=None, null=True, upload_to='hiren/%Y/%m/%d')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
    ]
