# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('has_cover', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0, validators=[music.models.validate_range])),
                ('favorite', models.BooleanField(default=False)),
                ('offline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='B2Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=200)),
                ('api_url', models.URLField()),
                ('download_url', models.URLField()),
                ('upload_url', models.URLField(null=True)),
                ('bucket_id', models.CharField(max_length=100, null=True)),
                ('bucket_dir', models.CharField(max_length=50, null=True)),
                ('download_token', models.CharField(max_length=200, null=True)),
                ('upload_token', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('artist', models.CharField(max_length=200, null=True, unique=True)),
                ('youtube', models.URLField(null=True, unique=True)),
                ('location', models.CharField(default='', max_length=500)),
                ('rating', models.IntegerField(default=0, validators=[music.models.validate_range])),
                ('favorite', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('offline', models.BooleanField(default=False)),
                ('genre', models.CharField(choices=[('Fok', 'Folk'), ('Jaz', 'Jazz'), ('Blu', 'Blues'), ('Cls', 'Classical'), ('Roc', 'Rock'), ('Pop', 'Pop'), ('Mel', 'Melody'), ('Hip', 'Hip Hop'), ('Orc', 'Orchestra'), ('Opr', 'Opera'), ('Con', 'Country'), ('Ins', 'Instrumental'), ('Tec', 'Techno'), ('Amb', 'Ambient'), ('HMe', 'Heavy Metal'), ('Dis', 'Disco'), ('EDa', 'Euro Dance'), ('Met', 'Metal'), ('Com', 'Comedy'), ('Mov', 'Movie'), ('Rel', 'Religious'), ('Rim', 'Remix'), ('Und', 'Undefined')], default='Und', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.Playlist'),
        ),
    ]
