# Generated by Django 2.1.1 on 2018-09-08 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('artist', models.CharField(max_length=200, null=True, unique=True)),
                ('youtube', models.URLField(null=True, unique=True)),
                ('location', models.CharField(default='', max_length=500)),
                ('rating', models.IntegerField(default=0, validators=[music.models.validate_range])),
                ('favorite', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('offline', models.BooleanField(default=False)),
                ('genre', models.CharField(choices=[('Fok', 'Folk'), ('Jaz', 'Jazz'), ('Blu', 'Blues'), ('Cls', 'Classical'), ('Roc', 'Rock'), ('Pop', 'Pop'), ('Mel', 'Melody'), ('Hip', 'Hip Hop'), ('Orc', 'Orchestra'), ('Opr', 'Opera'), ('Con', 'Country'), ('Ins', 'Instrumental'), ('Tec', 'Techno'), ('Amb', 'Ambient'), ('HMe', 'Heavy Metal'), ('Dis', 'Disco'), ('EDa', 'Euro Dance'), ('Met', 'Metal'), ('Com', 'Comedy'), ('Mov', 'Movie'), ('Rel', 'Religious'), ('Rim', 'Remix'), ('Und', 'Undefined')], default='Und', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.Album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='track',
            field=models.ManyToManyField(to='music.Track'),
        ),
    ]
