# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20160622_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.Playlist'),
        ),
    ]
