# Generated by Django 2.1.1 on 2018-09-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180908_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='archived',
            new_name='archive',
        ),
        migrations.AddField(
            model_name='track',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
