# Generated by Django 2.1.1 on 2018-09-16 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0004_auto_20180908_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('picture', models.ImageField(null=True, upload_to='image/musician')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='has_cover',
        ),
        migrations.AddField(
            model_name='album',
            name='picture',
            field=models.ImageField(null=True, upload_to='image/album'),
        ),
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='music.Musician'),
        ),
        migrations.AddField(
            model_name='track',
            name='musician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='music.Musician'),
        ),
    ]
