# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20160701_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='dropbox_id',
            field=models.CharField(max_length=500),
        ),
    ]
