# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20160703_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_art',
        ),
        migrations.RemoveField(
            model_name='music',
            name='dropbox_id',
        ),
        migrations.AddField(
            model_name='album',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='location',
            field=models.CharField(default='', max_length=500),
        ),
    ]
