# Generated by Django 2.1.1 on 2018-09-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20180918_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
    ]
