# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20160705_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='rating',
            field=models.IntegerField(default=0, validators=[music.models.validate_range]),
        ),
        migrations.AddField(
            model_name='album',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.CharField(choices=[('Fok', 'Folk'), ('Jaz', 'Jazz'), ('Blu', 'Blues'), ('Cls', 'Classical'), ('Roc', 'Rock'), ('Pop', 'Pop'), ('Mel', 'Melody'), ('Hip', 'Hip Hop'), ('Orc', 'Orchestra'), ('Opr', 'Opera'), ('Con', 'Country'), ('Ins', 'Instrumental'), ('Tec', 'Techno'), ('Amb', 'Ambient'), ('HMe', 'Heavy Metal'), ('Dis', 'Disco'), ('EDa', 'Euro Dance'), ('Met', 'Metal'), ('Com', 'Comedy'), ('Mov', 'Movie'), ('Rel', 'Religious'), ('Und', 'Undefined')], default='Und', max_length=3),
        ),
        migrations.AddField(
            model_name='music',
            name='rating',
            field=models.IntegerField(default=0, validators=[music.models.validate_range]),
        ),
        migrations.AddField(
            model_name='music',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.Album'),
        ),
        migrations.AlterField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
