# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20170313_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='music',
            name='youtube',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(choices=[('Fok', 'Folk'), ('Jaz', 'Jazz'), ('Blu', 'Blues'), ('Cls', 'Classical'), ('Roc', 'Rock'), ('Pop', 'Pop'), ('Mel', 'Melody'), ('Hip', 'Hip Hop'), ('Orc', 'Orchestra'), ('Opr', 'Opera'), ('Con', 'Country'), ('Ins', 'Instrumental'), ('Tec', 'Techno'), ('Amb', 'Ambient'), ('HMe', 'Heavy Metal'), ('Dis', 'Disco'), ('EDa', 'Euro Dance'), ('Met', 'Metal'), ('Com', 'Comedy'), ('Mov', 'Movie'), ('Rel', 'Religious'), ('Rim', 'Remix'), ('Und', 'Undefined')], default='Und', max_length=3),
        ),
    ]
