# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20170314_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='location',
        ),
    ]
