# Generated by Django 2.1.1 on 2018-09-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20180924_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='b2_file_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='tmp_upload',
            field=models.FileField(null=True, upload_to='music'),
        ),
        migrations.AlterField(
            model_name='track',
            name='youtube',
            field=models.URLField(null=True),
        ),
    ]
