# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_remove_album_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=200)),
                ('api_url', models.URLField()),
                ('download_url', models.URLField()),
                ('upload_url', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
