# Generated by Django 2.1.1 on 2018-09-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20180924_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='tmp_upload',
        ),
        migrations.AddField(
            model_name='track',
            name='download',
            field=models.FileField(null=True, upload_to='music/download/'),
        ),
        migrations.AddField(
            model_name='track',
            name='upload',
            field=models.FileField(null=True, upload_to='music/upload/'),
        ),
    ]
