# Generated by Django 2.1.1 on 2018-09-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20180924_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='b2_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
