# Generated by Django 2.1.1 on 2018-09-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_track_b2_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='location',
        ),
    ]
