language: python
python:
  - "3.6"

cache: pip


addons:
  postgresql: "9.6"

env:
  - DEBUG=True

install:
  - pip install -r requirements.txt --quiet
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py test
  - coverage run manage.py test

after_success:
- coveralls