language: python
python:
  - "3.6"

cache: pip

addons:
  postgresql: "9.3"

install:
  - pip install -r requirements.txt --quiet
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py test
  - coverage run --source=music manage.py test music
  - coverage run --source=base manage.py test base

after_success: coveralls
