# Generated by Django 2.1.1 on 2018-09-08 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=200)),
                ('api_url', models.URLField()),
                ('download_url', models.URLField()),
                ('upload_url', models.URLField(null=True)),
                ('bucket_id', models.CharField(max_length=100, null=True)),
                ('bucket_dir', models.CharField(max_length=50, null=True)),
                ('download_token', models.CharField(max_length=200, null=True)),
                ('upload_token', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
