# Generated by Django 2.1.1 on 2018-09-11 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_b2account'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2account',
            name='auth_token_validity',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
