# Generated by Django 2.1.1 on 2018-09-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_b2account_auth_token_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2account',
            name='app_key',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2account',
            name='app_key_id',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
