# Generated by Django 2.1.1 on 2018-09-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180911_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2account',
            name='api_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='b2account',
            name='auth_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='b2account',
            name='auth_token_validity',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='b2account',
            name='download_url',
            field=models.URLField(null=True),
        ),
    ]
