# Generated by Django 2.1.1 on 2018-09-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180913_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2account',
            name='upload',
            field=models.BooleanField(default=True),
        ),
    ]
