# Generated by Django 2.1.1 on 2018-09-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_b2account_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2account',
            name='verification',
            field=models.BooleanField(null=True),
        ),
    ]
