# Generated by Django 2.1.1 on 2018-09-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_setting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2account',
            name='upload_token_validity',
            field=models.DateTimeField(null=True),
        ),
    ]
